---
title: "Trabajo_final_R"
format: html
editor: visual
---
```{r}
library(readr)
ds_airbnb <- read_delim("Documents/Bootcamp/PROYECTO FINAL/airbnb-listings.csv", delim = ";", escape_double = FALSE, na = "NA", trim_ws = TRUE)
head(ds_airbnb)

```
```{r}
summary(ds_airbnb)
```

```{r}
colnames(ds_airbnb)
```

```{r}
ds_airbnb_work <- ds_airbnb[,(colnames(ds_airbnb) %in% c('ID','Hosts ID','Host Since','Host Listing Count','Host Total Listing Count','Neighbourhood Cleansed', 'Neighbourhood Group Cleansed', 'City','State', 'Zipcode', 'Market', 'Smart Location', 'Country Code','Country','Latitude', 'Longitude', 'Property Type', 'Room Type','Accommodates', 'Bathrooms', 'Bedrooms', 'Beds', 'Bed Type','Price','Weekly Price', 'Security Deposit','Cleaning Fee', 'Guests Included', 'Extra People', 'Number of Reviews', 'First Review','Last Review','Review Scores Rating', 'Review Scores Accuracy','Review Scores Cleanliness','Reviews Scores Chekin', 'Review Scores Communication','Review Scores Location','Review Scores Value', 'Cancellation Policy','Calculated host listings count','Reviews per Month','Geolocation'))]
```

```{r}
head(ds_airbnb_work)
```

```{r}
```


```{r}
summary(ds_airbnb_work)
```

```{r}
library(dplyr)
ds_airbnb_city <- ds_airbnb_work %>% count(State, sort = TRUE)
ds_airbnb_city
# No veo que ninguna de las columnas identifique bien a Madrid.Creo que sería necesario crear una columna donde se indique que es Madrid a los registros que tengan "Madrid" en State y luego filtrar solo por Madrid".

```

```{r}

# Si la columna State contiene 'Madrid' poner 'Madrid' sino "NoMadrid"



```

